# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Evan's Website"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/evan_photo.jpg"
float_logo: true # true, false (default)

icon: "/assets/images/ES_logo.jpg"

# blog cover
cover: "/assets/images/cover_photo.jpg"

name: 'Dirk Fabisch'
author: 'Dirk Fabisch'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#   share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/Eceptonsu/
    desc: Check out my github
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/evan-shi-cs/
    desc: Connect with me through linkedin
    share_url:
    share_title:
    share_link:

  - icon:  instagram
    url: https://www.instagram.com/eceptonsu/
    desc: Check out my instagram
    share_url:
    share_title:
    share_link:
